version: '3.9'
services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: qwe
      POSTGRES_PASSWORD: qwe
      POSTGRES_DB: qwe
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Server=db;Port=5432;Database=qwe;User Id=qwe;Password=qwe;"
volumes:
  db-data:
